name: CI

on:
  push:
    branches:
      - main

jobs:
  setup-runner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup self-hosted runner
      run: |
        chmod +x setup_runner.sh
        ./setup_runner.sh

  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run your build commands
      run: |
        # Your build commands here

